language: php
php:
  - 5.4
  - 5.5
  - 5.6
install:
  - composer self-update
  - composer install --dev
before_script:
  - sh ./build/ci/createEnvFile.sh 
  - chmod +x ./vendor/bin/behat
script:
  - phpunit
  - ./vendor/bin/behat