language: php
php:
  - 5.4
  - 5.5
  - 5.6
install:
  - composer self-update
  - composer install
before_script:
  - sh ./build/ci/createEnvFile.sh
  - sh ./build/ci/createSqliteFile.sh
  - chmod +x ./vendor/bin/behat
  - chmod +x ./vendor/bin/phpunit
  - php artisan migrate
script:
  - ./vendor/bin/phpunit --colors
  - ./vendor/bin/behat